version: "3"
services:

  php:
    build:
      context: ./php-fpm
    container_name: php_fpm
    depends_on:
      - postgres
    ports:
      - 9000:9000
    volumes:
      - ../guybrush:/var/www/html/guybrush
      - ./php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
      # - ./php-fpm/etc/php.ini:/usr/local/etc/php/php.ini

  # composer:
  #   image: composer:latest
  #   command: install
  #   volumes:
  #     - ../guybrush:/app:delegated
  #     - guybrush_var:/var/www/html/guybrush/var

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    depends_on: 
      - php
    ports:
      - "8080:80"
    volumes:
      - ../guybrush:/usr/share/nginx/html/guybrush
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  postgres:
    image: postgis/postgis
    container_name: postgres
    depends_on: 
      - php
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: guybrush
      POSTGRES_USER: guybrush_usr
      POSTGRES_PASSWORD: Pa55w0rD
    
  nginx_template:
    image: nginx
    container_name: nginx_template
    ports:
      - "8081:80"
    volumes:
      - type: bind
        source: ../html_template
        target: /usr/share/nginx/html
        consistency: cached
        read_only: true   

volumes:
  pgdata: