version: "3.2"
services:

  php:
    build:
      context: ./php-fpm
    container_name: php_fpm
    depends_on:
      - postgres
    # ports:
    #   - 9000:9000
    volumes:
      - type: bind
        source: ../guybrush
        target: /var/www/html/guybrush
        consistency: cached
        read_only: true
      - guybrush_var:/var/www/html/guybrush/var
      - ./php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
      # - ./php-fpm/etc/php.ini:/usr/local/etc/php/php.ini

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    depends_on: 
      - php
    ports:
      - "8080:80"
    volumes:
      - type: bind
        source: ../guybrush
        target: /usr/share/nginx/html/guybrush
        consistency: cached
        read_only: true
      - guybrush_var:/usr/share/nginx/html/guybrush/var
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  postgres:
    image: postgis/postgis
    container_name: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: guybrush
      POSTGRES_USER: guybrush_usr
      POSTGRES_PASSWORD: Pa55w0rD

volumes:
  guybrush_var:
  pgdata: