version: "3"
services:

  php:
    build:
      context: ./php-fpm
    container_name: php_fpm
    ports:
      - 9000:9000
    volumes:
      - ../guybrush:/var/www/html
      - ./php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
      # - ./php-fpm/etc/php.ini:/usr/local/etc/php/php.ini

  nginx:
    image: nginx
    container_name: nginx
    depends_on: 
      - php
    ports:
      - "8080:8080"
    volumes:
      - ../guybrush:/usr/share/nginx/html
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  postgres:
    image: postgis/postgis
    container_name: postgres
    depends_on: 
      - php
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: guybrush
      POSTGRES_USER: guybrush_usr
      POSTGRES_PASSWORD: Pa55w0rD

volumes:
  pgdata: