version: "3.2"
services:

  php:
    build:
      context: ./php-fpm
    container_name: php_fpm
    depends_on:
      - postgres
    volumes:
      - type: bind
        source: ../guybrush
        target: /var/www/html/guybrush
        consistency: cached
      - guybrush_var:/var/www/html/guybrush/var
      - ./php-fpm/etc/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php-fpm/etc/php/php.ini:/usr/local/etc/php/php.ini
      - ./php-fpm/etc/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    # Da Docker 20 in poi...
    # extra_hosts:
    #   - "host.docker.internal:gateway"
    environment: 
      - PHP_IDE_CONFIG=serverName=guybrush-docker
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    depends_on: 
      - php
    ports:
      - "8080:80"
    volumes:
      - type: bind
        source: ../guybrush
        target: /usr/share/nginx/html/guybrush
        consistency: cached
        read_only: true
      - guybrush_var:/usr/share/nginx/html/guybrush/var
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  postgres:
    image: postgis/postgis
    container_name: postgres
    ports:
      - "54320:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: guybrush
      POSTGRES_USER: guybrush_usr
      POSTGRES_PASSWORD: Pa55w0rD

volumes:
  guybrush_var:
  pgdata:
